import puppeteer from "puppeteer";
import { getSettings } from "./settingsService"; // ✅ Settings importieren

export async function generateHtmlPdf(order: any) {
  // 1. Settings laden
  const settings = await getSettings();

  // 2. Browser starten
  import puppeteer from 'puppeteer';

  // ... in deiner Funktion ...
  const browser = await puppeteer.launch({
    headless: true,
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
      "--disable-gpu",
    ],
    executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined, // WICHTIG!
  });
  // 3. HTML generieren (Jetzt mit Variablen aus 'settings'!)
  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: sans-serif; padding: 40px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .company-info { text-align: right; font-size: 0.9em; color: #666; }
        .company-name { font-size: 1.5em; font-weight: bold; color: #000; margin-bottom: 5px; }
        .title { font-size: 2em; font-weight: bold; margin-bottom: 10px; }
        .meta { margin-bottom: 30px; }
        .meta-item { margin-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { text-align: left; background: #f4f4f4; padding: 10px; border-bottom: 2px solid #ddd; }
        td { padding: 10px; border-bottom: 1px solid #eee; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #eee; text-align: center; font-size: 0.8em; color: #888; }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="title">Production Sheet</div>
          <div class="meta-item"><strong>Order:</strong> #${order.id.slice(0, 8)}</div>
          <div class="meta-item"><strong>Date:</strong> ${new Date(order.created_at).toLocaleDateString()}</div>
          <div class="meta-item"><strong>Customer:</strong> ${order.customer_name}</div>
        </div>
        <div class="company-info">
          <div class="company-name">${settings.company_name}</div>
          <div>${settings.address_line1 || ""}</div>
          <div>${settings.address_line2 || ""}</div>
          <div>${settings.email || ""}</div>
          <div>${settings.phone || ""}</div>
        </div>
      </div>

      <h3>Order Items</h3>
      <table>
        <thead>
          <tr>
            <th>Product</th>
            <th>Color</th>
            <th>Size</th>
            <th>Quantity</th>
            <th>Branding</th>
          </tr>
        </thead>
        <tbody>
          ${order.items.map((item: any) => `
            <tr>
              <td>${item.products?.name || "Unknown Product"}</td>
              <td>${item.color}</td>
              <td>${item.size}</td>
              <td><strong>${item.quantity}</strong></td>
              <td>${item.branding_method} (${item.branding_position})</td>
            </tr>
          `).join("")}
        </tbody>
      </table>

      <div class="footer">
        ${settings.footer_text || "Generated by Miktool Automation"}
      </div>
    </body>
    </html>
  `;

  await page.setContent(htmlContent);
  const pdfBuffer = await page.pdf({ format: "A4", printBackground: true });

  await browser.close();
  return pdfBuffer;
}