"use client"

import * as React from "react"
import { Separator } from "@/components/ui/separator"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Download, RefreshCw, Loader2 } from "lucide-react"
import { ConfiguratorCanvas } from "@/components/tools/ConfiguratorCanvas"
import { toast } from "sonner"
import { getProducts } from "@/lib/api"
import { Product } from "@/types/product"
import Konva from "konva"
// 👇 NEU: jsPDF importieren
import { jsPDF } from "jspdf"

export default function ConfiguratorPage() {
  const [products, setProducts] = React.useState<Product[]>([])
  const [isLoading, setIsLoading] = React.useState(true)
  const [selectedProductId, setSelectedProductId] = React.useState<string>("")
  const [selectedColor, setSelectedColor] = React.useState<string>("")
  const [selectedView, setSelectedView] = React.useState<string>("front")
  const [logoUrl, setLogoUrl] = React.useState<string | null>(null)

  const stageRef = React.useRef<Konva.Stage>(null)

  React.useEffect(() => {
    async function loadData() {
      try {
        const data = await getProducts()
        setProducts(data)
        if (data.length > 0) {
          setSelectedProductId(data[0].id)
          const firstAsset = data[0].product_assets?.[0]
          if (firstAsset?.color) setSelectedColor(firstAsset.color)
        }
      } catch (error) {
        console.error("Failed to load products:", error)
        toast.error("Could not load products.")
      } finally {
        setIsLoading(false)
      }
    }
    loadData()
  }, [])

  const currentProduct = products.find(p => p.id === selectedProductId)
  const availableAssets = currentProduct?.product_assets || []
  const availableColors = Array.from(new Set(availableAssets.map(a => a.color).filter(Boolean))) as string[]
  
  const currentAsset = availableAssets.find(
    a => a.color === selectedColor && a.view === selectedView
  ) || availableAssets[0]

  const baseImage = currentAsset ? currentAsset.base_image : null

  const handleProductChange = (id: string) => {
    setSelectedProductId(id)
    const prod = products.find(p => p.id === id)
    const firstColor = prod?.product_assets?.[0]?.color
    if (firstColor) setSelectedColor(firstColor)
  }

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      const url = URL.createObjectURL(file)
      setLogoUrl(url)
      toast.success("Logo uploaded successfully")
    }
  }

  // 👇 NEU: PDF Generierung statt Bild-Download
  const handleDownload = () => {
    if (!stageRef.current) return

    try {
      // 1. Canvas zu Bild konvertieren (Hohe Qualität)
      const imgData = stageRef.current.toDataURL({ 
          pixelRatio: 2 
      })

      // 2. PDF erstellen (A4 Format)
      const pdf = new jsPDF({
          orientation: "portrait",
          unit: "mm",
          format: "a4"
      })

      // 3. Header & Metadaten schreiben
      const now = new Date().toLocaleDateString()
      
      pdf.setFontSize(22)
      pdf.text("Product Design Preview", 20, 20)
      
      pdf.setFontSize(10)
      pdf.setTextColor(100)
      pdf.text(`Created on: ${now}`, 20, 26)

      // Produkt Details Box
      pdf.setDrawColor(200)
      pdf.setFillColor(245, 245, 245)
      pdf.rect(20, 35, 170, 25, "F") // Graue Box

      pdf.setFontSize(12)
      pdf.setTextColor(0)
      pdf.text(`Product:  ${currentProduct?.name || "Unknown"}`, 25, 45)
      pdf.text(`Variant:  ${selectedColor} / ${selectedView}`, 25, 52)

      // 4. Das Bild einfügen
      const pageWidth = pdf.internal.pageSize.getWidth()
      const margin = 20
      const imgWidth = pageWidth - (margin * 2) // Volle Breite minus Margins
      const imgHeight = imgWidth // Da unser Canvas quadratisch (1:1) ist

      pdf.addImage(imgData, "PNG", margin, 70, imgWidth, imgHeight)

      // Footer
      pdf.setFontSize(10)
      pdf.setTextColor(150)
      pdf.text("Generated by Miktool Inc.", margin, 280)

      // 5. Speichern
      pdf.save(`design-${currentProduct?.name}-${selectedColor}.pdf`)
      
      toast.success("PDF saved successfully!")
    } catch (err) {
      console.error(err)
      toast.error("Failed to generate PDF")
    }
  }

  if (isLoading) {
    return (
      <div className="flex h-full items-center justify-center">
         <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    )
  }

  return (
      <div className="flex flex-1 flex-col lg:flex-row h-[calc(100vh-4rem)] overflow-hidden">
        
        {/* LEFT PANEL: Settings */}
        <div className="w-full lg:w-80 border-r bg-background p-6 flex flex-col gap-6 overflow-y-auto">
          <div>
            <h2 className="text-lg font-semibold mb-1">Configuration</h2>
            <p className="text-sm text-muted-foreground">Customize your product.</p>
          </div>

          <div className="space-y-4">
            <div className="space-y-2">
              <Label>Product</Label>
              <Select value={selectedProductId} onValueChange={handleProductChange}>
                <SelectTrigger>
                  <SelectValue placeholder="Select Product" />
                </SelectTrigger>
                <SelectContent>
                  {products.map(p => (
                    <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="grid grid-cols-2 gap-4">
               <div className="space-y-2">
                  <Label>Color</Label>
                  <Select value={selectedColor || ""} onValueChange={setSelectedColor} disabled={availableColors.length === 0}>
                    <SelectTrigger><SelectValue placeholder="Color" /></SelectTrigger>
                    <SelectContent>
                      {availableColors.map(c => (
                        <SelectItem key={c} value={c}>{c}</SelectItem>
                      ))}
                      {availableColors.length === 0 && <SelectItem value="none" disabled>No colors</SelectItem>}
                    </SelectContent>
                  </Select>
               </div>
               <div className="space-y-2">
                  <Label>View</Label>
                  <Select value={selectedView} onValueChange={setSelectedView}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="front">Front</SelectItem>
                      <SelectItem value="back">Back</SelectItem>
                    </SelectContent>
                  </Select>
               </div>
            </div>

            <Separator className="my-2" />

            <div className="space-y-2">
              <Label>Upload Logo</Label>
              <div className="grid w-full max-w-sm items-center gap-1.5">
                <Input 
                  id="logo" 
                  type="file" 
                  accept="image/*"
                  onChange={handleLogoUpload}
                />
              </div>
              <p className="text-xs text-muted-foreground">Supported: PNG, JPG, SVG</p>
            </div>
          </div>

          <div className="mt-auto pt-4 flex gap-2">
              <Button 
                variant="outline" 
                className="flex-1"
                onClick={() => setLogoUrl(null)}
              >
                  <RefreshCw className="mr-2 h-4 w-4" /> Reset
              </Button>
              <Button className="flex-1" onClick={handleDownload}>
                  <Download className="mr-2 h-4 w-4" /> PDF Export
              </Button>
          </div>
        </div>

        {/* RIGHT PANEL: Live Preview */}
        <div className="flex-1 bg-zinc-50/50 dark:bg-zinc-900/50 flex flex-col items-center justify-center p-8 overflow-auto">
           <div className="shadow-2xl rounded-lg overflow-hidden border bg-white min-h-[500px] min-w-[500px] flex items-center justify-center">
              {baseImage ? (
                  <ConfiguratorCanvas 
                    ref={stageRef} 
                    baseImageUrl={baseImage} 
                    logoUrl={logoUrl} 
                  />
              ) : (
                  <div className="text-muted-foreground text-sm">Select a product to view preview</div>
              )}
           </div>
           
           {baseImage && (
             <p className="text-sm text-muted-foreground mt-6 flex items-center gap-2">
                <span className="inline-block w-2 h-2 rounded-full bg-blue-500 animate-pulse"></span>
                Interactive Preview: Drag & resize the logo.
             </p>
           )}
        </div>
      </div>
  )
}